Add unit/functional tests and coverage checks (#185)
Testing related changes:

* Add unit tests for particular classes used by plugins (e.g. configuration model base class, attribute classes).
* Add functional tests for running Buildarr end-to-end when using it for a variety of scenarios.
* Update the `dummy` plugin, and add a new `dummy2` plugin, for use in the functional tests (hidden when not in testing mode).
* Add JUnit unit test metadata generation.
* Add Coverage.py coverage metadata generation (current result is 91% coverage).
* Update the GitHub Actions test workflow to run tests against both Ubuntu and Windows, using all supported Python versions (3.8-3.12), and report pass-fail/coverage results.
* Update all other GitHub Actions jobs to run using Python 3.12.

As a result of the testing added by this PR, fix a variety of bugs, and make a number of improvements:

* Fix Python 3.12 support by replacing usage of the removed `distutils.util.strtobool` function.
* Fix Windows support for the `buildarr compose` command, by converting native Windows paths returned by plugins to Unix paths suitable for running in Docker Desktop.
* Instead of a `str`, accept a 2-tuple or 3-tuple for representing short-form Docker volume syntax (splitting Windows paths using the `str`-based format was too troublesome).
* Add support for handling the `SIGBREAK` signal on Windows.
* Fix capitalisation on the daemon `--update-day` valid values list.
* Improve error message when an invalid daemon `--update-day` value is supplied.
* Make the `buildarr.trash_metadata_dir_prefix` configuration attribute nullable, to improve support for custom TRaSH metadata URLs.
* To make operations against all plugins deterministic, change `state.active_plugin` to a sorted `tuple` instead of a `frozenset`, and update a couple of loops to iterate over sorted lists of elements.
* Implement the `url_base` attribute in the `ConfigBase` base class, so plugins do not have to implement it separately.
    * Plugins should remove their separate implementation of this field when upgrading to the new version.
* Remove some redundant code.
* Fix an issue where `TrashID` fields will allow invalid characters to be defined in configuration files.

Other changes:

* Update copyright on all files.
* Remove some now-redundant linter silencing.
* Fix some minor metadata errors in `pyproject.toml`.
* Upgrade PDM to 2.15.0.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,7 +15,7 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: "3.11"
+          python-version: "3.12"
           cache: "pip"
       - name: Run pre-commit hooks
         uses: pre-commit/action@v3.0.1
@@ -31,7 +31,8 @@ jobs:
       - name: Setup Python and PDM
         uses: pdm-project/setup-pdm@v4
         with:
-          python-version: "3.11"
+          python-version: "3.12"
+          version: "2.15.0"
       - name: Build source dist and wheels
         run: pdm build --verbose
       - name: Upload source dist and wheels to artifacts
@@ -41,3 +42,73 @@ jobs:
           path: dist/
           retention-days: 5
           if-no-files-found: error
+
+  test:
+    needs: pre-commit
+    permissions:
+      checks: write
+    strategy:
+      fail-fast: false
+      matrix:
+          operating_system:
+            - ubuntu-22.04
+            - windows-2022
+          python_version:
+            - "3.8"
+            - "3.9"
+            - "3.10"
+            - "3.11"
+            - "3.12"
+    runs-on: ${{ matrix.operating_system }}
+    steps:
+      - name: Clone full tree, and checkout branch
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Setup Python and PDM
+        uses: pdm-project/setup-pdm@v4
+        with:
+          python-version: ${{ matrix.python_version }}
+          version: "2.15.0"
+      - name: Create virtual environment
+        run: pdm install
+      - name: Run tests
+        run: pdm run test
+      - name: Publish test results
+        uses: mikepenz/action-junit-report@v4
+        # Always run, even if the tests fail.
+        if: success() || failure()
+        with:
+          report_paths: rspec.xml
+      - name: Upload coverage report to artifacts
+        uses: actions/upload-artifact@v4
+        # Always run, even if the tests fail.
+        if: success() || failure()
+        with:
+          name: coverage-${{ matrix.operating_system}}-${{ matrix.python_version }}
+          path: coverage.xml
+          retention-days: 5
+          if-no-files-found: warn
+
+  coverage:
+    needs: test
+    # Always run, even if the test job failed.
+    if: success() || failure()
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Download coverage reports from artifacts
+        uses: actions/download-artifact@v4
+        with:
+          pattern: coverage-*
+          merge-multiple: false
+      - name: Generate code coverage summary report
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: coverage-*/coverage.xml
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: false
+          indicators: false
+          output: both
+      - name: Write to job summary
+        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
